name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.6
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Setup test database
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost"
          RAILS_ENV: test
        run: bundle exec rails db:setup

      - name: Run default task
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost"
          RAILS_ENV: test
        run: bundle exec rake
